name: PlatformIO CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  PlatformIO-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.16'
      - name: Install PlatformIO
        run: python -m pip install --upgrade pip platformio
      - run: platformio check --fail-on-defect low --fail-on-defect medium --fail-on-defect high --skip-packages

#  PlatformIO-CI:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - name: Set up Python
#        uses: actions/setup-python@v5
#      - name: Install PlatformIO
#        run: python -m pip install --upgrade pip platformio
#      - run: platformio ci --lib="." --board=ttgo-lora32-v1 --board=d1_mini examples/basic_decode

  PlatformIO-NativeTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.16'
      - name: Install PlatformIO
        run: python -m pip install --upgrade pip platformio
      - run: platformio test -e native

  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run clang-format style check for C/C++ programs.
        uses: jidicula/clang-format-action@v4.10.2
        with:
          clang-format-version: '14'
          check-path: src
